### ISSUE TITLE
RuntimeError: You can't initialize an object twice!

### ISSUE THREAD

**Issue by ovo-Tim** [haiiliin/pyqtribbon#51]
I just copied the code from [User Manual](https://pyqtribbon.haiiliin.com/en/stable/user.html#id2).
But I met a problent
``` bash
Traceback (most recent call last):
  File "/pyqtribbo/first.py", line 20, in <module>
    category1 = ribbonbar.addCategory('Category 1')
  File "/home/tim/mambaforge/lib/python3.10/site-packages/pyqtribbon/ribbonbar.py", line 401, in addCategory
    else RibbonNormalCategory(title, self)
  File "/home/tim/mambaforge/lib/python3.10/site-packages/pyqtribbon/category.py", line 327, in __init__
    super().__init__(title, RibbonCategoryStyle.Normal, parent=parent)
  File "/home/tim/mambaforge/lib/python3.10/site-packages/pyqtribbon/category.py", line 197, in __init__
    super().__init__(parent)
  File "/home/tim/mambaforge/lib/python3.10/site-packages/pyqtribbon/category.py", line 44, in __init__
    super().__init__(parent)
RuntimeError: You can't initialize an object twice!
```
Is that a bug?

**Comment by haiiliin** [comment]
Yes, I somehow add two lines of `super().__init__(parent)`, I don not know it works in my machine!
